### ISSUE TITLE
Bug: docker-telemetry-watchdog Cargo.lock is a stub, dependencies are re-resolved on every build

### ISSUE THREAD

**Issue by devesh-nexthop** [sonic-net/sonic-buildimage#29369]
### Is it platform specific

generic

### Importance or Severity

High

### Description of the bug

`dockers/docker-telemetry-watchdog/watchdog/Cargo.lock` is a stub: one package entry named `watchdog` (the crate in `Cargo.toml` is `telemetry_watchdog`), no dependency entries, no checksums. Cargo discards it and re-resolves the whole dependency tree from crates.io at build time, so `docker-telemetry-watchdog` builds against whatever versions are published that day. When `tinyvec 1.13.0` (transitively: `url = "=2.4.1"` → `idna` → `unicode-normalization`) was published, it did not compile on the rustc 1.79.0 pinned in `Dockerfile.j2` and every rebuild of `target/docker-telemetry-watchdog.gz` failed.

### Steps to Reproduce

```
rustup toolchain install 1.79.0
cd dockers/docker-telemetry-watchdog/watchdog
cargo build --release
```

### Actual Behavior and Expected Behavior

Actual: the dependency tree is resolved fresh on each build; a bad upstream crate release breaks the image build for unrelated changes.

Expected: the committed `Cargo.lock` pins the resolved tree, and the build fails loudly rather than re-resolving if the lockfile is stale.

### Relevant log output

```shell
error: cannot find macro `vec` in this scope
   --> .../tinyvec-1.13.0/src/tinyvec.rs:710:21
note: `vec` is imported here, but it is a module, not a macro
error: could not compile `tinyvec` (lib) due to 1 previous error
make: *** [slave.mk:1218: target/docker-telemetry-watchdog.gz] Error 1
```

### Output of `show version`, `show techsupport`

```shell
N/A - build-time failure.
```
