### ISSUE TITLE
After upgrade Click version from 7.0 to 8.1.3 sonic-utilities compiling failed

### ISSUE THREAD

**Issue by SandyLiu1115** [sonic-net/sonic-buildimage#14057]
After upgrade Click version from 7.0 to 8.1.3 sonic-utilities compiling failed

#### Steps to reproduce the issue:
1.upgrade click version from 7.0 to 8.1.3 in sonic-utilities
install_requires=[
        'click==8.1.3',
2.Compiling sonic-utilities

#### Describe the results you received:
Build failed:
=========================== short test summary info ============================
ERROR tests/aaa_test.py - TypeError: __init__() got an unexpected keyword argument 'autocompletion'
ERROR tests/acl_config_test.py - TypeError: __init__() got an unexpected keyword argument 'autocompletion'
ERROR tests/buffer_test.py - TypeError: __init__() got an unexpected keyword argument 'autocompletion'
ERROR tests/chassis_modules_test.py - TypeError: __init__() got an unexpected keyword argument 'autocompletion'
ERROR tests/cli_autogen_test.py - TypeError: __init__() got an unexpected keyword argument 'autocompletion'
ERROR tests/config_an_test.py - TypeError: __init__() got an unexpected keyword argument 'autocompletion'
ERROR tests/config_int_name_test.py - TypeError: __init__() got an unexpected keyword argument 'autocompletion'
ERROR tests/console_test.py - TypeError: __init__() got an unexpected keyword argument 'autocompletion'
ERROR tests/db_migrator_test.py - TypeError: __init__() got an unexpected keyword argument 'autocompletion'
ERROR tests/drops_group_test.py - TypeError: __init__() got an unexpected keyword argument 'autocompletion'
ERROR tests/fgnhg_test.py - TypeError: __init__() got an unexpected keyword argument 'autocompletion'
ERROR tests/flow_counter_stats_test.py - TypeError: __init__() got an unexpected keyword argument 'autocompletion'
ERROR tests/intfstat_test.py - TypeError: __init__() got an unexpected keyword argument 'autocompletion'
ERROR tests/ip_config_test.py - TypeError: __init__() got an unexpected keyword argument 'autocompletion'
ERROR tests/pgdropstat_test.py - TypeError: __init__() got an unexpected keyword argument 'autocompletion'
ERROR tests/portchannel_test.py - TypeError: __init__() got an unexpected keyword argument 'autocompletion'
ERROR tests/portstat_test.py - TypeError: __init__() got an unexpected keyword argument 'autocompletion'
ERROR tests/radius_test.py - TypeError: __init__() got an unexpected keyword argument 'autocompletion'
ERROR tests/synchronous_mode_test.py - TypeError: __init__() got an unexpected keyword argument 'autocompletion'
ERROR tests/tpid_test.py - TypeError: __init__() got an unexpected keyword argument 'autocompletion'
ERROR tests/vlan_test.py - TypeError: __init__() got an unexpected keyword argument 'autocompletion'
ERROR tests/dump_tests/dump_state_test.py - TypeError: __init__() got an unexpected keyword argument 'autocompletion'

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```
